# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_text',
            field=models.TextField(),
        ),
    ]
