# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20170627_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_description',
            field=models.TextField(blank=True),
        ),
    ]
